[package]
name = "blog_os"
version = "0.1.0"
edition = "2018"
authors = ["Author Name <petersonyuhala@gmail.com>"]

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"